version: '3.8'

services:
  # Redis for Bull Queue system - development config
  redis:
    image: redis:7-alpine
    container_name: jewelry-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-dev-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped

  # Redis Commander for development
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: jewelry-redis-ui-dev
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped


volumes:
  redis-dev-data:
    driver: local

networks:
  default:
    name: jewelry-dev-network
    driver: bridge
